# Generated by Django 2.1.5 on 2019-01-05 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата изменения')),
                ('text', models.TextField(max_length=300, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'История изменения',
                'verbose_name_plural': 'История изменений',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(verbose_name='Дата создания')),
                ('last_modify', models.DateField(verbose_name='Дата последнего изменения')),
                ('text', models.TextField(max_length=300, verbose_name='Текст сообщения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgapp.Message', verbose_name='Сообщение'),
        ),
    ]
